---
nft_input_host_rules:
  400 allow dns:
    - tcp dport { 53 } ct state new accept
    - udp dport { 53 } ct state new accept
  401 allow adguard webui:
    - tcp dport { 80 } ct state new accept
  402 allow adguard-sync webui:
    - tcp dport { 8080 } ct state new accept

# Nmap scan report for adguard1.pantheon.lab.mpgn.dev (10.80.50.111)
# Host is up (0.00014s latency).
# Not shown: 996 closed tcp ports (reset)
# PORT     STATE SERVICE
# 22/tcp   open  ssh
# 53/tcp   open  domain
# 80/tcp   open  http
# 8080/tcp open  http-proxy
# MAC Address: BC:24:11:11:32:49 (Unknown)