---
nft_input_host_rules: []

# Nmap scan report for freepbx.pantheon.lab.mpgn.dev (10.80.50.131)
# Host is up (0.00013s latency).
# Not shown: 994 closed tcp ports (reset)
# PORT     STATE SERVICE
# 22/tcp   open  ssh
# 80/tcp   open  http
# 443/tcp  open  https
# 1720/tcp open  h323q931
# 8001/tcp open  vcom-tunnel
# 8089/tcp open  unknown
# MAC Address: BC:24:11:1A:DD:10 (Unknown)