---
nft_input_host_rules: []

# Nmap scan report for homarr.pantheon.lab.mpgn.dev (10.80.50.106)
# Host is up (0.00015s latency).
# Not shown: 998 closed tcp ports (reset)
# PORT    STATE SERVICE
# 22/tcp  open  ssh
# 443/tcp open  https
# MAC Address: BC:24:11:03:8F:A1 (Unknown)