---
nft_input_host_rules:
  400 librenms web interface:
    - tcp dport { 80, 443, 42217 } ct state new accept

# Nmap scan report for librenms-web.pantheon.lab.mpgn.dev (10.80.50.109)
# Host is up (0.00013s latency).
# Not shown: 997 closed tcp ports (reset)
# PORT    STATE SERVICE
# 22/tcp  open  ssh
# 80/tcp  open  http
# 443/tcp open  https
# MAC Address: BC:24:11:BA:22:D0 (Unknown)