---
nft_input_host_rules:
  400 librenms backend services:
    - tcp dport { 3306, 11211, 6379 } ct state new accept
    
# Nmap scan report for librenms.pantheon.lab.mpgn.dev (10.80.50.105)
# Host is up (0.00013s latency).
# Not shown: 997 closed tcp ports (reset)
# PORT     STATE SERVICE
# 22/tcp   open  ssh
# 111/tcp  open  rpcbind
# 3306/tcp open  mysql
# MAC Address: BC:24:11:67:B1:2C (Unknown)